server:
  port: 18104
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  zipkin:
    base-url: localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.11.130/guli_sms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.11.130
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu.gmall.sms: debug