server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8179
        dashboard: http://localhost:8080
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.130:3306/guli_ums
    password: root
    username: root
  redis:
    host: 192.168.11.130
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.ums.entity
feign:
  sentinel:
    enabled: true